name: jest-ci-server

on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:16
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: carbone
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Connect to PostgreSQL
        run: npm run test
        env:
          JWT_SECRET_KEY: MA_SUPER_CLEF
